name: Pino-iOS
options:
  bundleIdPrefix: com.aurora.pino
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    majorVersion: 9.0.0
  OHHTTPStubs:
    url: https://github.com/AliSoftware/OHHTTPStubs
    majorVersion: 9.0.0
settings:
  IPHONEOS_DEPLOYMENT_TARGET: "15.0"
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
targets:
  Pino-iOS:
    scheme:
      configVariants:
    type: application
    platform: iOS
    sources:
      - Pino-iOS
    settings:
      base:
        INFOPLIST_FILE: Pino-iOS/App/Info.plist
        
        CODE_SIGN_STYLE: Manual
      configs:
          Debug:
              CODE_SIGN_IDENTITY: "iPhone Developer"
              PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]: "match Development com.aurora.pino.Pino-iOS"
              DEVELOPMENT_TEAM[sdk=iphoneos*]: "44E38FYW6J"
          Release:
              CODE_SIGN_IDENTITY: "iPhone Distribution"
              PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]: "match AppStore com.aurora.pino.Pino-iOS"
              DEVELOPMENT_TEAM[sdk=iphoneos*]: "44E38FYW6J"
  Pino-iOSTests:
    scheme:
      testTargets:
        - Pino-iOSTests
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: Pino-iOSTests
      - package: OHHTTPStubs
        product: OHHTTPStubs
        product: OHHTTPStubsSwift
    sources:
      - Pino-iOSTests
    settings:
      base:
        INFOPLIST_FILE: Pino-iOS/App/Info.plist
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Pino-iOS.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Pino-iOS"
  Pino-iOSUITests:
    scheme:
      testTargets:
        - Pino-iOSUITests
    type: bundle.ui-testing
    dependencies:
      - target: Pino-iOSUITests
    platform: iOS
    sources:
      - Pino-iOSUITests
    settings:
      base:
        INFOPLIST_FILE: Pino-iOS/App/Info.plist
        TEST_TARGET_NAME: "Pino-iOS"

    
